### ISSUE TITLE
What is KanbitMQ?

### ISSUE THREAD

**Issue by Eddcapone** [AdobeDocs/commerce-operations.de-DE#2]
In the german translation it says KanbitMQ instead of RabbitMQ. In german Rabbit means Kanin btw, it would match somewhat with Kanbit

![image](https://user-images.githubusercontent.com/16349349/201945811-bac15da9-57dc-41c0-a316-59a4484f5096.png)

Issue in ./help/installation/prerequisites/rabbitmq.md

**Comment by yanlicao** [comment]
Hi @Eddcapone , thank you very much for your feedback.
We are tracking this issue via ticket G11N-11131.
Will keep you posted.

**Comment by yanlicao** [comment]
Hi @Eddcapone , this is now resolved. Please verify, it should reads RabbitMQ now.  Thank you very much for your feedback again.

**Comment by yanlicao** [comment]
Close as fixed.

**Comment by Eddcapone** [comment]
@yanlicao , yes, it is correct now, good job!

**Comment by yanlicao** [comment]
@Eddcapone you are welcome and thanks for your valuable input :)
