### ISSUE TITLE
Composer should not be translated

### ISSUE THREAD

**Issue by Eddcapone** [AdobeDocs/commerce-operations.de-DE#3]
Issue in ./help/installation/system-requirements.md

"Composer" is translated in german to "Verfasser". It should be something that should not be translated.

**Comment by yanlicao** [comment]
Dear @Eddcapone  Thank you for your feedback. 
This is being reviewed and tracked in G11N-11962.

**Comment by yanlicao** [comment]
Dear @Eddcapone , this bug is now fixed, please verify, here is an screenshot for your reference.
I will close this ticket, thanks again for your feedback.
![image](https://user-images.githubusercontent.com/2255096/224347711-1fbc1b02-f80d-4293-b84e-2fad39f20e8b.png)
